### ISSUE TITLE
Create mockups

### ISSUE THREAD

**Issue by danixeee** [danixeee/CSMProject#3]
Create mockups for Main page, Dialogs, Tasks, Diagrams, etc.

**Comment by davidmilivojev** [comment]
![1pocetna](https://cloud.githubusercontent.com/assets/24207193/21545979/f5292296-cddb-11e6-9b79-b1f51dc5c0ba.png)
![2korisnik](https://cloud.githubusercontent.com/assets/24207193/21545981/f56e3b7e-cddb-11e6-8fc9-97d7f6d5036c.png)
![3kalendar](https://cloud.githubusercontent.com/assets/24207193/21545982/f56e78e6-cddb-11e6-8494-de10d527638f.png)
![4problems](https://cloud.githubusercontent.com/assets/24207193/21545980/f56cea76-cddb-11e6-9ccd-95be76ea9a18.png)
